# Generated by Django 4.1.2 on 2022-10-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chequeImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(blank=True, null=True)),
                ('chequeNo', models.PositiveIntegerField(blank=True, null=True)),
                ('micrCode', models.PositiveIntegerField(blank=True, null=True)),
                ('rbiAccNo', models.PositiveIntegerField(blank=True, null=True)),
                ('transactionCode', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserbankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accNo', models.CharField(blank=True, max_length=20, null=True)),
                ('accHolderName', models.CharField(blank=True, max_length=20, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('phoneNumber', models.PositiveBigIntegerField(blank=True, null=True)),
                ('balance', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Bounced', 'Bounced')], max_length=20, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('accNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userbankinfo')),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cheque')),
            ],
        ),
        migrations.AddField(
            model_name='cheque',
            name='accHolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userbankinfo'),
        ),
    ]
