# Generated by Django 4.1.2 on 2022-11-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='chequeImage',
            field=models.ImageField(blank=True, null=True, upload_to='cheque/'),
        ),
    ]
