# Generated by Django 4.1.2 on 2022-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cheque_chequeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='amountImage',
            field=models.ImageField(blank=True, null=True, upload_to='amount/'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='amountWordsImage',
            field=models.ImageField(blank=True, null=True, upload_to='amountWords/'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='dateImage',
            field=models.ImageField(blank=True, null=True, upload_to='date/'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='nameImage',
            field=models.ImageField(blank=True, null=True, upload_to='name/'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='signatureImage',
            field=models.ImageField(blank=True, null=True, upload_to='signature/'),
        ),
    ]
