# Generated by Django 4.1.2 on 2022-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cheque_amountimage_cheque_amountwordsimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
