# Generated by Django 4.1.2 on 2022-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userbankinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='accnoImage',
            field=models.ImageField(blank=True, null=True, upload_to='accno/'),
        ),
    ]
